export const INIT_FILE_UPLOADING = 'INIT_FILE_UPLOADING';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';
export const UPDATE_FILE_UPLOADING_PROGRESS = 'UPDATE_FILE_UPLOADING_PROGRESS';
export const REMOVE_FILE = 'REMOVE_FILE';
export const NOTIFY = 'NOTIFY';
